'use client';

import { Container } from '@mui/material';
import { Fragment } from 'react';
import Header from '@/layouts/header';
import Footer from '@/layouts/footer';

// export const metadata = {
//   title: 'Login | Minum Kopi',
//   description: 'Generated by create next app'
// };

const Index = () => {
  return (
    <Fragment>
      <Header page="login" />
      <Container
        maxWidth="lg"
        sx={{
          '@media (max-width: 599px)': {
            paddingTop: '3rem'
          },
          '@media (min-width: 600px)': {
            paddingTop: '4rem'
          }
        }}
      >
        <h1>Login Page</h1>
      </Container>
      <Footer page="login" />
    </Fragment>
  );
};

export default Index;
