import Homes from '@/app/homes';

export const metadata = {
  title: 'Aplikasi Pesan Kopi Kekinian | Minum Kopi',
  description: 'Generated by create next app',
  manifest: '/minum-kopi/manifest.json'
};

export default function Home() {
  return <Homes />;
}
