export const metadata = {
  title: 'Favorite | Minum Kopi',
  description: 'Generated by create next app'
};

import Header from '@/layouts/header/displayName';
import Footer from '@/layouts/footer';
import { Container } from '@mui/material';
import { Fragment } from 'react';

const Index = () => {
  return (
    <Fragment>
      <Header />
      <Container
        maxWidth="lg"
        sx={{
          paddingTop: { xs: '3rem', sm: '4rem' }
        }}
      >
        <h1>Favorite Page</h1>
      </Container>
      <Footer />
    </Fragment>
  );
};

export default Index;
